added solution for task 04-MeetupPageDraft
js-tasks-ru/vue-20210304_warma2d pull request #2
Opened 2021-04-08 19:10 UTC by warma2d

2021-04-08 19:10 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-08 20:33 UTC, ShGKme requested changes
Требуется избавиться от вызова методов в шаблоне. Это не грубая ошибка (и иногда это нормально), но в начале важно разобраться с вычисляемыми свойствами и концепцией шаблона, декларирующего представление приложения.

2021-04-08 20:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +    </title>
Директивы Vue работают только в шаблоне Vue приложения.
title - не часть шаблона (и не может им быть).

2021-04-08 20:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +        <div class="meetup-cover" :style="'background: no-repeat url( ' + imageUrl + ') '">
Чтобы не пришлось переписывать весь целиком background фона, в котором много всего (например, градиент для затемнения) предлагается использовать кастомное css свойство (aka css переменную) с ссылкой на изображение. И переопределять только ссылку.

https://github.com/js-tasks-ru/vue-course-materials/blob/master/01-basics/index.html#L110
https://github.com/js-tasks-ru/vue-course-materials/blob/master/01-basics/script.js#L62

(Можно описывать сразу в шаблоне и строкой, а не объектом. Здесь просто рассматривали разные варианты)

2021-04-08 20:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +                                <p v-if="item.description">{{ item.description }}</p>
Лучше избегать вызова методов в шаблоне.
Здесь может быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут перевычисляться  только тогда, когда изменяются свойства, от которых они зависят.

Кроме того, это не декларативно. Нам требуется описать шаблон, который декларирует, описывает, какое отображение (HTML) мы хотим получить. А вызов метода - это императивный путь, мы говорим, что нужно сделать, чтобы получить данные, необходимые для формирования страницы.

Здесь очень простой метод, вызов второго не влияет на производительность, но вызов метода заставляет думать, а точно ли это так.

Лучше либо написать здесь же простое выражение (для получения иконки нам, например, надо только к свойству объекта обратиться), либо сделать вычисляемое свойство, которое на основе данных программы вернёт новую программу, дополненную нужными для шаблона данными.

2021-04-08 20:33 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/README.md
> +  - Изображение (при наличии), ссылку на которое можно получить по https://course-vue.javascript.ru/api/images/4
Изменять условие задачи не требуется :)

2021-04-10 06:14 UTC, warma2d commented on 01-basics/04-MeetupPageDraft/index.html
> +                                <p v-if="item.description">{{ item.description }}</p>
Хорошо, идея ясна, нужно использовать вычисляемое свойство или выражение. Но как это технически можно сделать? Ведь здесь в цикле вызывается метод getAgendaIcon(item.type), то есть для каждого элемента получаем свою иконку, что логично. А откуда вычисляемое свойство будет знать какая сейчас итерация и какой agenda icon использовать?

2021-04-10 06:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-10 07:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-04-10 11:39 UTC, ShGKme approved these changes
Принято

2021-04-10 11:39 UTC, merged

2021-04-10 11:41 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +                                <p v-if="item.description">{{ item.description }}</p>
Технически - так же, как в вашем решении. Либо вычисляемое свойство, которое возвращает программу с дополнительными/обновлёнными данными. Либо добавить в область видимости шаблона только объект с иконками и объект с заголовками. Ведь всё, что делает getAgendaIcon(item.type) - это одно действие - обратиться к полю `item.type` объекта с иконками и вернуть значение. Обратиться к полю объекта можно и в шаблоне. Нужно только, чтобы объект был в области видимости шаблона